# Illya-BOICHUK-Camp-2025

## Homework lesson 3: Pandas

## Answer 1

In [23]:
import pandas as pd
import numpy as np

def answer_one():
    energy_data = pd.read_excel('data/Energy Indicators.xls', usecols="C:F")
    energy_df = pd.DataFrame(energy_data)
    energy_df.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    energy_df = energy_df[17:244]
    energy_df['Energy Supply'] = energy_df['Energy Supply'].apply(lambda x: x * 1_000_000 if isinstance(x, int) else x)
    energy_df = energy_df.replace('...', np.nan).infer_objects(copy=False)
    
    country_name_mapping = {
        'Republic of Korea': 'South Korea',
        'United States of America': 'United States',
        'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
        'China, Hong Kong Special Administrative Region': 'Hong Kong'
    }
    
    energy_df['Country'] = energy_df['Country'].str.replace(r' \(.*\)|[0-9]', '', regex=True)
    energy_df['Country'] = energy_df['Country'].replace(country_name_mapping)

    gdp_data = pd.read_excel('data/world_bank.xls', sheet_name='Data', skiprows=3)
    gdp_df = pd.DataFrame(gdp_data)
    
    gdp_country_mapping = {
        'Korea, Rep.': 'South Korea',
        'Iran, Islamic Rep.': 'Iran',
        'Hong Kong SAR, China': 'Hong Kong'
    }
    
    gdp_df['Country Name'] = gdp_df['Country Name'].replace(gdp_country_mapping)
    gdp_df = gdp_df.drop(gdp_df.columns[1:50], axis=1)
    gdp_df = gdp_df.drop(gdp_df.columns[11:18], axis=1)

    scimago_data = pd.read_excel('data/scimagojr.xlsx')
    scimago_df = pd.DataFrame(scimago_data)
    scimago_df = scimago_df[scimago_df['Rank'] <= 15]

    merged_df = pd.merge(scimago_df, energy_df, on='Country', how='inner')
    merged_df = pd.merge(merged_df, gdp_df, left_on='Country', right_on='Country Name', how='inner')
    
    merged_df.drop('Country Name', axis=1, inplace=True)
    merged_df.drop('Region', axis=1, inplace=True)
    merged_df.set_index('Country', inplace=True)
    
    return merged_df

answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,273437,272374,2336764,1615239,8.55,245,1.271910e+11,93.0,19.754910,2.752119e+12,3.550328e+12,4.594337e+12,5.101691e+12,6.087192e+12,7.551545e+12,8.532186e+12,9.570471e+12,1.047562e+13,1.106157e+13
United States,2,175891,172431,2230544,724472,12.68,363,9.083800e+10,286.0,11.570980,1.381559e+13,1.447423e+13,1.476986e+13,1.447806e+13,1.504896e+13,1.559973e+13,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13
India,3,55082,53775,463165,162944,8.41,181,3.319500e+10,26.0,14.969080,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856721e+12,2.039126e+12,2.103588e+12
Japan,4,50523,50065,488062,119930,9.66,193,1.898400e+10,149.0,10.232820,4.601663e+12,4.579750e+12,5.106679e+12,5.289494e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
United Kingdom,5,43389,42284,615670,111290,14.19,226,7.920000e+09,124.0,10.600470,2.709978e+12,3.092996e+12,2.931684e+12,2.417566e+12,2.491397e+12,2.666403e+12,2.706341e+12,2.786315e+12,3.065223e+12,2.934858e+12
Germany,6,38739,38013,433148,95145,11.18,196,1.326100e+10,165.0,17.901530,2.994704e+12,3.425578e+12,3.745264e+12,3.411261e+12,3.399668e+12,3.749315e+12,3.527143e+12,3.733805e+12,3.889093e+12,3.357586e+12
Russian Federation,7,36735,36560,115938,54993,3.16,90,3.070900e+10,214.0,17.288680,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
Canada,8,33472,32863,568080,100953,16.97,227,1.043100e+10,296.0,61.945430,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
Italy,9,27983,26940,352993,87828,12.61,166,6.530000e+09,109.0,33.667230,1.949552e+12,2.213102e+12,2.408655e+12,2.199929e+12,2.136100e+12,2.294994e+12,2.086958e+12,2.141924e+12,2.162010e+12,1.836638e+12
South Korea,10,27655,27445,328488,61531,11.88,155,1.100700e+10,221.0,2.279353,1.053217e+12,1.172614e+12,1.047339e+12,9.439419e+11,1.144067e+12,1.253223e+12,1.278428e+12,1.370795e+12,1.484318e+12,1.465773e+12
France,11,25232,24732,343860,65734,13.63,178,1.059700e+10,166.0,17.020280,2.320536e+12,2.660591e+12,2.930304e+12,2.700887e+12,2.645188e+12,2.865158e+12,2.683672e+12,2.811877e+12,2.855964e+12,2.439189e+12
Iran,12,22933,22734,307280,97038,13.40,141,9.172000e+09,119.0,5.707721,2.662989e+11,3.498816e+11,4.123362e+11,4.163970e+11,4.868076e+11,6.261331e+11,6.440355e+11,4.927756e+11,4.603828e+11,4.082129e+11
Spain,13,21955,21597,352497,64588,16.06,176,4.923000e+09,106.0,37.968590,1.260399e+12,1.474003e+12,1.631863e+12,1.491473e+12,1.422108e+12,1.480710e+12,1.324751e+12,1.355580e+12,1.371821e+12,1.196157e+12
Brazil,14,21524,21236,183915,45172,8.54,127,1.214900e+10,59.0,69.648030,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12
Australia,15,20614,20147,314307,51583,15.25,176,5.386000e+09,231.0,11.810810,7.479074e+11,8.544273e+11,1.055686e+12,9.286298e+11,1.148570e+12,1.398456e+12,1.546953e+12,1.576330e+12,1.467590e+12,1.350580e+12

# Answer 2

In [24]:
def answer_two():
    Top15 = answer_one()
    avgGDP = Top15.loc[:, '2006':'2015'].mean(axis=1).sort_values(ascending=False)
    return avgGDP
answer_two()

Country
United States         1.570403e+13
China                 6.927707e+12
Japan                 5.239642e+12
Germany               3.523342e+12
United Kingdom        2.780276e+12
France                2.691337e+12
Italy                 2.142986e+12
Brazil                1.988889e+12
Russian Federation    1.666746e+12
Canada                1.616359e+12
India                 1.602352e+12
Spain                 1.400886e+12
South Korea           1.221372e+12
Australia             1.207513e+12
Iran                  4.563261e+11
dtype: float64

# Answer 3

In [25]:
def answer_three():
    Top15 = answer_one()
    avgGDP = answer_two()
    sixth_largest_country = avgGDP.index[5]
    gdp_change = Top15.loc[sixth_largest_country, '2015'] - Top15.loc[sixth_largest_country, '2006']
    return gdp_change
answer_three()

118652421857.7959

# Answer 4

In [26]:
def answer_four():
    Top15 = answer_one()
    Top15['Citation Ratio'] = Top15['Citations'] / Top15['Self-citations']
    max_ratio_country = Top15['Citation Ratio'].idxmax()
    max_ratio_value = Top15['Citation Ratio'].max()
    
    return (max_ratio_country, max_ratio_value)
answer_four()

('Australia', 6.093228389197992)

# Answer 5

In [27]:
def answer_five():
    Top15 = answer_one()
    Top15['Population Estimate'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15 = Top15.sort_values(by='Population Estimate', ascending=False)
    third_most_populous_country = Top15.index[2]

    return third_most_populous_country
answer_five()

'United States'

# Answer 6

In [28]:
def answer_six():
    Top15 = answer_one()
    Top15['Citable Documents per Capita'] = Top15['Citable documents'] / (Top15['Energy Supply'] / Top15['Energy Supply per Capita'])
    correlation = Top15['Citable Documents per Capita'].corr(Top15['Energy Supply per Capita'])
    return correlation
answer_six()

0.7434709127726777

# Answer 7

In [29]:
def answer_seven():
    Top15 = answer_one()
    ContinentDict = {'China':'Asia', 
                     'United States':'North America', 
                     'Japan':'Asia', 
                     'United Kingdom':'Europe', 
                     'Russian Federation':'Europe', 
                     'Canada':'North America', 
                     'Germany':'Europe', 
                     'India':'Asia',
                     'France':'Europe', 
                     'South Korea':'Asia', 
                     'Italy':'Europe', 
                     'Spain':'Europe', 
                     'Iran':'Asia',
                     'Australia':'Australia', 
                     'Brazil':'South America'}
    
    continent_df = pd.DataFrame(list(ContinentDict.items()), columns=['Country', 'Continent'])
    Top15 = pd.merge(Top15, continent_df, on='Country')
    Top15['Population Estimate'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    result = Top15.groupby('Continent')['Population Estimate'].agg(['size', 'sum', 'mean', 'std'])
    return result
answer_seven()

               size           sum          mean           std
Continent
Asia              5  2.898666e+09  5.797333e+08  6.790979e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            6  4.579297e+08  7.632161e+07  3.464767e+07
North America     2  3.528552e+08  1.764276e+08  1.996696e+08
South America     1  2.059153e+08  2.059153e+08           NaN